version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: crypto_trader_app
    container_name: crypto_trader_app
    volumes:
      - .:/workspaces/CryptoTrader

  binance_miner:
    image: crypto_trader_app
    container_name: binance_miner_bot
    working_dir: /workspaces/CryptoTrader
    volumes:
      - .:/workspaces/CryptoTrader
    depends_on:
      - app
    command: >
      bash -c "/venv/bin/python3 scripts/download_binance_crypto_data.py"
