version: "3.8"

services:
  mySQL:
    image: mysql:latest
    container_name: mySQL
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql_data:/var/lib/mysql
      - ./data/etc/mysql/my.conf:/etc/mysql/my.conf
