version: "3.8"

services:
  mySQL:
    image: mysql:latest
    container_name: mySQL
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql_data:/var/lib/mysql

  mysql-backup:
    build:
      context: . # Caminho onde está o Dockerfile (diretório atual)
      dockerfile: Dockerfile # Caso o nome do Dockerfile seja diferente
    container_name: mysql-backup
    volumes:
      - ./backups:/backups # Volume para persistir os backups
    entrypoint: /bin/sh -c "while true; do sleep 86400; done" # Loop para manter o container rodando
    depends_on:
      - mySQL
