version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cryptotrader_container
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=database
    depends_on:
      - mySQL

  mySQL:
    image: mysql:latest
    container_name: cryptotrader_mySQL
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ../data/mysql_data:/var/lib/mysql
      - ../data/etc/mysql/my.conf:/etc/mysql/my.conf
